name: test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  schedule:
    - cron: '0 0 */16 * *'  
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: ubuntu

    services:
      private_node:
        image: wavesplatform/waves-private-node
        ports:
          - 6869:6869

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0

      - name: Install Surfboard
        run:  npm install --location=global @waves/surfboard

      - name: Run tests
        run:  node "$(npm root --location=global)/@waves/surfboard/bin/run" test
