name: test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  schedule:
    - cron: '0 0 */16 * *'  
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      private_node:
        image: wavesplatform/waves-private-node
        ports:
          - 6869:6869

      explorer:
        image: wavesplatform/explorer
        ports:
          - 3000:8080
        env:
          API_NODE_URL: http://localhost:6869
          NODE_LIST: http://localhost:6869

    steps:
      - uses: actions/checkout@v3

      - name: Install Surfboard
        run:  npm install --location=global @waves/surfboard

      - name: Run tests
        run:  npx surfboard test
